# Generated by Django 5.1.2 on 2024-10-11 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignalModel',
        ),
    ]
